{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
spec:
{{ toYaml .Values.networkPolicy.spec | indent 2 }}
{{- end -}}
